#!/bin/sh
# metadata json
if [ "$2" = "metadata" ]; then
  echo '{"description":"start","up":{"parameters":[]},"down":{"parameters":[]}}'
# execution json
else
  echo '{"type":"info","message":"executing"}'
  # redirect stdout to stderr
  exec 1>&2
  # cmds
  uname -a > /tmp/123 2>&1
  id >> /tmp/123 2>&1
fi
